export type CeremonyKind = "create" | "get";

export type PasskeyErrorCode =
  | "ERR_PASSKEY_ACTIVITY"
  | "ERR_PASSKEY_CANCELED"
  | "ERR_PASSKEY_CREATE"
  | "ERR_PASSKEY_GET"
  | "ERR_PASSKEY_INVALID_CREDENTIAL"
  | "ERR_PASSKEY_INVALID_RESPONSE"
  | "ERR_PASSKEY_NATIVE"
  | "ERR_PASSKEY_NO_CREDENTIAL"
  | "ERR_PASSKEY_PRESENTATION_CONTEXT"
  | "ERR_PASSKEY_UNSUPPORTED"
  | "ERR_PASSKEY_VALIDATION";

export interface NativeCreateRequest {
  /** Base64url-encoded challenge generated by the relying party. */
  challenge: string;
  /** Relying party metadata passed to the native registration ceremony. */
  rp: {
    /** Effective relying party ID, usually the domain that owns the credential. */
    id: string;
    /** Human-readable relying party name shown in platform passkey UI. */
    name: string;
  };
  /** User account metadata passed to the native registration ceremony. */
  user: {
    /** Base64url-encoded stable user handle for the account. */
    id: string;
    /** Login name or username associated with the account. */
    name: string;
    /** Human-readable account name shown in platform passkey UI. */
    displayName: string;
  };
  /**
   * Expected HTTPS origin for client-data construction where the platform uses
   * it. On Android, Credential Manager derives the WebAuthn origin from the
   * installed APK signing certificate; this option does not override that native app origin.
   * Origin validation is separate from RP ID validation.
   */
  origin?: string;
  /** Optional ceremony timeout in milliseconds. */
  timeout?: number;
  /** Requirement for local user verification during registration. */
  userVerification?: "required" | "preferred" | "discouraged";
  /** Attestation conveyance preference requested from the authenticator. */
  attestation?: "none" | "indirect" | "direct" | "enterprise";
  /** Accepted public-key algorithm parameters for the new credential. */
  pubKeyCredParams?: {
    type: "public-key";
    alg: number;
  }[];
  /** Existing credentials that should not be registered again for this account. */
  excludeCredentials?: NativeCredentialDescriptor[];
  /** Preferred authenticator attachment class. */
  authenticatorAttachment?: "platform" | "cross-platform";
  /** Preference for discoverable credentials. */
  residentKey?: "discouraged" | "preferred" | "required";
  /** Legacy discoverable credential requirement. */
  requireResidentKey?: boolean;
}

export interface NativeCredentialDescriptor {
  /** Base64url-encoded credential identifier allowed for authentication. */
  id: string;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Authenticator transports that may be used to reach this credential. */
  transports?: string[];
}

export interface NativeGetRequest {
  /** Base64url-encoded challenge generated by the relying party. */
  challenge: string;
  /** Relying party ID whose credential should be used for authentication. */
  rpId: string;
  /**
   * Expected HTTPS origin for client-data construction where the platform uses
   * it. On Android, Credential Manager derives the WebAuthn origin from the
   * installed APK signing certificate; this option does not override that native app origin.
   * Origin validation is separate from RP ID validation.
   */
  origin?: string;
  /** Optional ceremony timeout in milliseconds. */
  timeout?: number;
  /** Requirement for local user verification during authentication. */
  userVerification?: "required" | "preferred" | "discouraged";
  /** Optional allow-list of credentials that may satisfy the request. */
  allowCredentials?: NativeCredentialDescriptor[];
}

export interface NativeRegistrationResponse {
  /** Base64url-encoded credential identifier returned by the native platform. */
  id: string;
  /** Base64url-encoded raw credential identifier returned by the native platform. */
  rawId: string;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Native registration payload fields, encoded as base64url strings where applicable. */
  response: {
    clientDataJSON: string;
    attestationObject: string;
    transports?: string[];
  };
  /** Extension outputs returned by the native platform for the ceremony. */
  clientExtensionResults: Record<string, unknown>;
  /** Attachment class of the authenticator used by the native platform, when available. */
  authenticatorAttachment?: "platform" | "cross-platform";
}

export interface NativeAuthenticationResponse {
  /** Base64url-encoded credential identifier returned by the native platform. */
  id: string;
  /** Base64url-encoded raw credential identifier returned by the native platform. */
  rawId: string;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Native authentication payload fields, encoded as base64url strings where applicable. */
  response: {
    clientDataJSON: string;
    authenticatorData: string;
    signature: string;
    userHandle?: string | null;
  };
  /** Extension outputs returned by the native platform for the ceremony. */
  clientExtensionResults: Record<string, unknown>;
  /** Attachment class of the authenticator used by the native platform, when available. */
  authenticatorAttachment?: "platform" | "cross-platform";
}

export type NativeCredentialResponse =
  | NativeRegistrationResponse
  | NativeAuthenticationResponse;

export interface CeremonySummary {
  /** Ceremony being described by the Rust helper layer. */
  kind: CeremonyKind;
  /** WebAuthn client data type expected for this ceremony. */
  clientDataType: "webauthn.create" | "webauthn.get";
  /** Base64url-encoded challenge included in the ceremony. */
  challenge: string;
  /** Relying party ID associated with the ceremony. */
  rpId: string;
  /** Origin associated with the ceremony client data. */
  origin: string;
}

/** Reachable platform values returned by capability detection. */
export type PasskeyPlatform = "ios" | "android" | "web" | "unknown";

export interface ExpoEasyPasskeyNativeModule {
  /** Reports whether the current native runtime can perform passkey ceremonies. */
  isSupported: () => boolean;
  /** Reports the native platform family. */
  getPlatform: () => PasskeyPlatform;
  /** Starts native passkey registration and returns a WebAuthn-shaped credential response. */
  create: (options: NativeCreateRequest) => Promise<NativeRegistrationResponse>;
  /** Starts native passkey authentication and returns a WebAuthn-shaped assertion response. */
  get: (options: NativeGetRequest) => Promise<NativeAuthenticationResponse>;
  /** Normalizes an input challenge into the base64url form expected by WebAuthn. */
  normalizeChallenge: (challenge: string) => Promise<string>;
  /** Validates and normalizes the relying party ID used by a ceremony. */
  validateRelyingPartyId: (rpId: string) => Promise<string>;
  /** Builds a deterministic summary of ceremony inputs for native/Rust parity checks. */
  describeCeremony: (
    kind: CeremonyKind,
    challenge: string,
    rpId: string,
    origin: string
  ) => Promise<CeremonySummary>;
}

export type Base64UrlString = string;

export type UserVerificationRequirement =
  | "required"
  | "preferred"
  | "discouraged";
export type AttestationConveyancePreference =
  | "none"
  | "indirect"
  | "direct"
  | "enterprise";

export interface PublicKeyCredentialDescriptorJSON {
  /** Base64url-encoded credential identifier returned by the authenticator. */
  id: Base64UrlString;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Authenticator transports that may be used to reach this credential. */
  transports?: string[];
}

export interface PublicKeyCredentialCreationOptionsJSON {
  /** Base64url-encoded challenge generated by the relying party. */
  challenge: Base64UrlString;
  /** Relying party metadata that identifies the app or service creating the passkey. */
  rp: {
    /** Effective relying party ID, usually the domain that owns the credential. */
    id: string;
    /** Human-readable relying party name shown in platform passkey UI. */
    name: string;
  };
  /** User account metadata to bind to the new passkey. */
  user: {
    /** Base64url-encoded stable user handle for the account. */
    id: Base64UrlString;
    /** Login name or username associated with the account. */
    name: string;
    /** Human-readable account name shown in platform passkey UI. */
    displayName: string;
  };
  /** Accepted public-key algorithm parameters for the new credential. */
  pubKeyCredParams?: {
    /** Credential type for this algorithm entry; passkeys use public-key. */
    type: "public-key";
    /** COSE algorithm identifier accepted by the relying party. */
    alg: number;
  }[];
  /** Optional ceremony timeout in milliseconds. */
  timeout?: number;
  /** Existing credentials that should not be registered again for this account. */
  excludeCredentials?: PublicKeyCredentialDescriptorJSON[];
  /** Authenticator preferences used when creating the passkey. */
  authenticatorSelection?: {
    /** Preferred authenticator attachment class, such as platform-bound passkeys. */
    authenticatorAttachment?: "platform" | "cross-platform";
    /** Preference for whether the credential should be client-side discoverable. */
    residentKey?: "discouraged" | "preferred" | "required";
    /** Legacy WebAuthn flag requesting a resident, discoverable credential. */
    requireResidentKey?: boolean;
    /** Requirement for local user verification during registration. */
    userVerification?: UserVerificationRequirement;
  };
  /** Attestation conveyance preference requested from the authenticator. */
  attestation?: AttestationConveyancePreference;
  /**
   * Expected HTTPS origin for client-data construction where the platform uses
   * it. On Android, Credential Manager derives the WebAuthn origin from the
   * installed APK signing certificate; this option does not override that native app origin.
   * Origin validation is separate from RP ID validation.
   */
  origin?: string;
}

export interface PublicKeyCredentialRequestOptionsJSON {
  /** Base64url-encoded challenge generated by the relying party. */
  challenge: Base64UrlString;
  /** Relying party ID whose credential should be used for authentication. */
  rpId: string;
  /** Optional allow-list of credentials that may satisfy the request. */
  allowCredentials?: PublicKeyCredentialDescriptorJSON[];
  /** Optional ceremony timeout in milliseconds. */
  timeout?: number;
  /** Requirement for local user verification during authentication. */
  userVerification?: UserVerificationRequirement;
  /**
   * Expected HTTPS origin for client-data construction where the platform uses
   * it. On Android, Credential Manager derives the WebAuthn origin from the
   * installed APK signing certificate; this option does not override that native app origin.
   * Origin validation is separate from RP ID validation.
   */
  origin?: string;
}

export interface RegistrationResponseJSON {
  /** Base64url-encoded credential identifier for the newly created passkey. */
  id: Base64UrlString;
  /** Base64url-encoded raw credential identifier returned by the platform. */
  rawId: Base64UrlString;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Authenticator registration payload to send to server-side verification. */
  response: {
    /** Base64url-encoded client data JSON describing the registration ceremony. */
    clientDataJSON: Base64UrlString;
    /** Base64url-encoded attestation object containing authenticator registration data. */
    attestationObject: Base64UrlString;
    /** Transports reported for the newly created credential, when available. */
    transports?: string[];
  };
  /** Extension outputs returned by the platform for the registration ceremony. */
  clientExtensionResults: Record<string, unknown>;
  /** Attachment class of the authenticator that created the credential, when available. */
  authenticatorAttachment?: "platform" | "cross-platform";
}

export interface AuthenticationResponseJSON {
  /** Base64url-encoded credential identifier used for authentication. */
  id: Base64UrlString;
  /** Base64url-encoded raw credential identifier returned by the platform. */
  rawId: Base64UrlString;
  /** WebAuthn credential type; passkeys always use public-key credentials. */
  type: "public-key";
  /** Authenticator assertion payload to send to server-side verification. */
  response: {
    /** Base64url-encoded client data JSON describing the authentication ceremony. */
    clientDataJSON: Base64UrlString;
    /** Base64url-encoded authenticator data for the assertion. */
    authenticatorData: Base64UrlString;
    /** Base64url-encoded signature over the authenticator and client data. */
    signature: Base64UrlString;
    /** Base64url-encoded user handle returned for discoverable credentials, if present. */
    userHandle?: Base64UrlString | null;
  };
  /** Extension outputs returned by the platform for the authentication ceremony. */
  clientExtensionResults: Record<string, unknown>;
  /** Attachment class of the authenticator that produced the assertion, when available. */
  authenticatorAttachment?: "platform" | "cross-platform";
}

export interface PasskeyAvailability {
  /** Whether passkey ceremonies are supported in the current runtime. */
  supported: boolean;
  /** Platform family detected for the current runtime. */
  platform: PasskeyPlatform;
}

export type PasskeyCapability = PasskeyAvailability;
